title: AppSec Israel 
description: OWASP AppSec Israel annual conference
title: AppSec Israel 
description: OWASP AppSec Israel annual conference

# Since GH pages override this to "true", we test this value to see if we are running locally
safe: false

current_year: 2026

plugins:
  - jekyll-redirect-from

defaults: 
  - scope: 
      path: "2023/*.md"
      type: "pages"
    values: 
      layout: layout-2023
      year: 2023
  - scope: 
      path: "2025/*.md"
    values: 
      year: 2025
      layout: layout-2025
  - scope: 
      path: "2026/*.md"
    values: 
      year: 2026
      layout: layout-2026
      permalink: /:basename:output_ext
