title: AppSec Israel&nbsp;2026
description: OWASP AppSec Israel annual conference - 2026 edition!

year: 2026

address: Tel Aviv Expo, Pavilion 10
# Conference dates
dates:
  conference: May 18, 2026
  cfpCloses: coming soon
  notification: coming soon

logoUrl: ./assets/img/2026/AppSecIL_2026_Logo.png

links:
  registration: https://appsecil2026.forms-wizard.biz/
  calendar: https://calendar.google.com/calendar/event?action=TEMPLATE&amp;tmeid=MmptcTBtMzVncWE5ZW5iMzc0NXJlb290MDMgN2MwNGNmODliZjE3MzliMjY1ZmQ5YjNjNTk5OGIyOTY4MmE1NTdlMDEwNGJiNGY1OWFkZTExMGEzNGQxMmUzYUBn&amp;tmsrc=7c04cf89bf1739b265fd9b3c5998b29682a557e0104bb4f59ade110a34d12e3a%40group.calendar.google.com
  cfp: https://www.papercall.io/owasp-il-2026
