title: AppSec Israel 2026
description: OWASP AppSec Israel annual conference - 2026 edition!

year: 2026

address: TBD
# Conference dates
dates:
  conference: TBD
  cfpCloses: TBD
  notification: TBD

logoUrl: ./assets/img/2025/AppSecIL_logo.png
