title: AppSec Israel&nbsp;2026
description: OWASP AppSec Israel annual conference - 2026 edition!

year: 2026

address: Tel Aviv Expo, Pavilion 10
# Conference dates
dates:
  conference: May 18, 2026
  cfpCloses: coming soon
  notification: coming soon

logoUrl: ./assets/img/2026/logo-temp.png
